CREATE SCHEMA BOOK_STORE;
USE BOOK_STORE;

CREATE TABLE BOOK_STORE (
  BOOK_ID bigint(20) NOT NULL,
  AUTHOR varchar(100) NOT NULL,
  DESCRIPTION varchar(500) DEFAULT NULL,
  GENRE varchar(255) DEFAULT NULL,
  ISBN varchar(13) NOT NULL,
  PRICE float NOT NULL,
  PUBLISH_DATE date DEFAULT NULL,
  SOLD_COPIES int(11) NOT NULL,
  TITLE varchar(255) NOT NULL,
  TOTAL_COPIES int(11) NOT NULL,
  PRIMARY KEY (BOOK_ID)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE BOOKS_PURCHASED (
  PURCHASE_ID bigint(20) NOT NULL,
  ISBN varchar(13) NOT NULL,
  NO_OF_COPIES int(11) NOT NULL,
  PURCHASE_DATE date NOT NULL,
  PRIMARY KEY (PURCHASE_ID)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE `hibernate_sequence` (
  `next_val` bigint(20) DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

